### ISSUE TITLE
Please add a license file and a readme.md

### ISSUE THREAD

**Issue by unixorn** [mpostaire/ztupide#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme that documents how to use them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by mpostaire** [comment]
I planned to do it but I'm too busy right now. I'll do it as soon as I can!

**Comment by unixorn** [comment]
NP. Either comment on this issue once it's done and I'll add it or make a PR directly on https://github.com/unixorn/awesome-zsh-plugins.

Thanks

**Comment by mpostaire** [comment]
It's done!
